#:schema https://mago.carthage.software/1.27.1/schema.json
# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
version = "1"
php-version = "8.4.0"
extends = "vendor/shlinkio/shlink-mago-config/mago.toml"

[source]
workspace = "."
paths = ["config", "src", "test"]
excludes = ["config/params"]
includes = ["vendor"]

[source.glob]
literal-separator = true

[linter.rules]
no-literal-password = { exclude = ["test"] }
no-empty-catch-clause = { exclude = ["test"] }
no-empty-loop = { exclude = ["test"] }

[analyzer]
baseline = "mago-analyze-baseline.toml"
